version: '3'
services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.dockerfile
        volumes:
            - ./:/var/www/
            - ./deploy/vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8081:80"
    app:
        build:
            context: ./
            dockerfile: deploy/app.dockerfile
        volumes:
            - ./:/var/www

#    database:
#        image: mysql:latest
#        environment:
#            - MYSQL_DATABASE=dockerdb
#            - MYSQL_ROOT_PASSWORD=secret
#            - MYSQL_USER=dockerapp
#            - MYSQL_PASSWORD=secret
#        ports:
#            - "33061:3306"
#        volumes:
#            - ./data/db/mysql:/var/lib/mysql
